a=float(input("Enter your first number (a):"))
b=float(input("Enter your second number (b):"))
print(f"Add your two numbers {a+b}")
print(f"Subtract b from a {b-a}")
print(f"Multiply a by b {a*b}")
print(f"Divide a by b {a/b}")
print(f"Perform integer division from a by b {a//b}")
print(f"find the remainder when a is divided by b {a%b}")
print(f"Calculate a raised to the power of b {a**b}")
