import turtle
import tkinter.simpledialog as simpledialog
window = turtle.Screen()
window.title("Turtle Graphics Example")
window.bgcolor("white")
theturtle = turtle.Turtle()
theturtle.pensize(3)
theturtle.color("blue")
theturtle.forward(100)
theturtle.right(90)
theturtle.forward(50)
theturtle.left(90)
theturtle.penup()               
theturtle.goto(50, 50)
theturtle.pendown()
theturtle.circle(25)
theturtle.dot(10)
theturtle.setheading(0)
theturtle.color("green")
theturtle.begin_fill()
for _ in range(4):
    theturtle.forward(50)
    theturtle.right(90)
theturtle.end_fill()
theturtle.clear()
theturtle.reset()
theturtle.hideturtle()
theturtle.showturtle()

